sonar.projectKey=pe-estudantes-back
sonar.projectName=EduTrace Backend

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.spec.ts,src/**/*.spec.ts
sonar.exclusions=coverage/**,prisma/migrations/**,node_modules/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPaths=tsconfig.json
sonar.sourceEncoding=UTF-8
