sonar.projectKey=pe-estudantes-front
sonar.projectName=EduTrace Frontend

sonar.sources=src
sonar.exclusions=.next/**,public/**,node_modules/**
sonar.typescript.tsconfigPaths=tsconfig.json
sonar.sourceEncoding=UTF-8
